{% set version = "2023.3.0" %}
package:
  name: intake-pattern-catalog
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/intake-pattern-catalog/intake-pattern-catalog-{{ version }}.tar.gz
  sha256: f237dc3005502b9d1b80b54585ae2fe8a2e93e454646df198d7100a0b76c1be7

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vvv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - intake

test:
  imports:
    - intake_pattern_catalog
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/DTN-Public/intake-pattern-catalog
  summary: Intake plugin for specifying a file-path pattern which can represent a number of different entries
  license_file: LICENSE.md
  license: BSD-3-Clause

extra:
  recipe-maintainers:
    - raybellwaves
    - tdhopper
    - blackary
